# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in aoc-2021.gemspec
# gemspec

gem "rake", "~> 13.0"

gem "minitest", "~> 5.0"

gem "rubocop", "~> 1.7"

gem "thor"